# Generated by Django 6.0.5 on 2026-06-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace_app', '0002_alter_offer_options_alter_offerdetail_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerdetail',
            name='delivery_time_in_days',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='offerdetail',
            name='revisions',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_time_in_days',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='revisions',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='offerdetail',
            unique_together={('offer', 'offer_type')},
        ),
    ]

